import type { Metadata } from "next";
import "./globals.css";

import Header from "./Header";
import { inter } from "./fonts";



export const metadata: Metadata = {
  title: "projekt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header />
      <main className="bg-sky-950 min-h-[calc(100vh_-_4rem)] py-16 px-[15vw]">{children}</main></body>
    </html>
  );
}
